Hotfix/changes barbearia
viniferraria/webarber-backend pull request #63
Opened 2020-11-01 00:54 UTC by zewuchen

# PR Description

#### Proposed changes

*Ajustado as issues #48 e #60*

#### Kind of Change
What kind of change does your code introduce? Put an ```x``` in the box that applies.
**NOTE: Please do not create MRs with different purposes. Each MR must have a single purpose: Hotfix, New Feature, or Structural Change.**

- [ ] Hotfix.    
- [ ] New Feature. 
- [ ] Structural Change.  

#### Checklist

Put an ```x``` in the boxes that apply.

### This MR follows the base conventions of the project:
- [ ] Does not add commented code.
- [ ] Does not add code with ```print```.
- [ ] Documentation have been added / updated as needed.
- [ ] Tests have been added / updated as needed.

### Tests:
- [ ] Tests are running at 70% coverage, with success and error cases for new features, bugs, and hotfixes.
- [ ] Does not apply to this MR

### Accessibility:
- [ ] Accessibility have been implemented or updated.
- [ ] Does not apply to this MR

### Third-Party Libraries:
- [ ] A new library? It's really neccessary? Explain why
- [ ] Does not apply to this MR

# Final checks:
- [ ] **All** tests have been executed and are succeeding.

2020-11-02 03:32 UTC, viniferraria commented on src/app/controllers/BarbeariaController.js
> -                    }
Acho que seria válido colocar um 'OR',  buscar uma barbearia que tenha o mesmo nome ou que tenha o mesmo moderador.
Aqui vai acabar permitindo que outro moderador crie uma barbearia com um nome já cadastrado.

2020-11-02 03:34 UTC, viniferraria commented on src/app/controllers/BarbeariaController.js
> +                return res.status(400).json({ message: 'Usuário já possui uma barbearia'});
Acho que retornar se o usuário já possui uma barbearia é uma falha de segurança, uma vez que permite que o atacante consulte se o usuário possui ou não

2020-11-02 03:35 UTC, viniferraria requested changes
Corrigir a validação na criação de barbearia

2020-11-02 12:40 UTC, zewuchen commented on src/app/controllers/BarbeariaController.js
> -                    }
Mas aí pode existir o caso de barbearias com o mesmo nome sim, tipo, sempre existe barbearia Phoenix com cnpj diferentes. Mas ainda sim são diferentes barbearias, e normalmente as filiais também segue o padrão com o mesmo nome, mudando só o CNPJ

2020-11-02 22:47 UTC, viniferraria commented on src/app/controllers/BarbeariaController.js
> -                    }
Não lembro de a gente ter discutido sobre isso.
@matheusaf

2020-11-02 22:51 UTC, matheusaf commented on src/app/controllers/BarbeariaController.js
> -                    }
Acho válido, porém precisaria de mais atributos para fazer essa diferenciação como, por exemplo, o cep.

2020-11-04 03:11 UTC, viniferraria approved these changes

2020-11-04 03:12 UTC, merged